resolve extra-2: spread props
alXmas/react-fundamentals pull request #5
Opened 2020-10-07 14:46 UTC by alXmas

2020-10-07 17:39 UTC, pvpshoot requested changes
Нужно доделать

2020-10-07 17:39 UTC, pvpshoot commented on src/exercise/03.html
> +    const element = React.createElement('div', {...props})
Тут подразумевается использовант jsx синтаксиса с спред оператором <div {...props}/>

2020-10-08 06:30 UTC, alXmas commented on src/exercise/03.html
> +    const element = React.createElement('div', {...props})
Исправил!

2020-10-09 08:14 UTC, pvpshoot approved these changes
👍

2020-10-09 08:22 UTC, merged